In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [50]:
data = pd.read_csv("https://raw.githubusercontent.com/mlsacbvp/BVEST_Beat_The_Base/main/BTB_dev.csv")
data.head()

,Unnamed: 0,object_id,ra,decl,ddf_bool,hostgal_specz,hostgal_photoz,hostgal_photoz_err,distmod,mwebv,...,true_vpec,true_rv,true_av,true_peakmjd,tflux_u,tflux_g,tflux_r,tflux_i,tflux_z,tflux_y
0,0,615,349.0461,-61.9438,1,0.000,0.000,0.000,-9.000,0.017,...,0.0,0.0,0.0,59570.000,484.7,3286.7,3214.1,3039.7,2854.5,2837.0
1,1,713,53.0859,-27.7844,1,1.818,1.627,0.255,45.406,0.007,...,0.0,0.0,0.0,59570.000,108.7,117.7,119.9,149.6,147.9,150.5
2,2,730,33.5742,-6.5796,1,0.232,0.226,0.016,40.256,0.021,...,4.5,0.0,0.0,60444.379,0.0,0.0,0.0,0.0,0.0,0.0
3,3,745,0.1899,-45.5867,1,0.304,0.281,1.152,40.795,0.007,...,257.7,0.0,0.0,60130.453,0.0,0.0,0.0,0.0,0.0,0.0
4,4,1124,352.7113,-63.8237,1,0.193,0.241,0.018,40.417,0.024,...,-368.8,0.0,0.0,60452.641,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
df = data.drop("Unnamed: 0", axis=1)

In [52]:
df

,object_id,ra,decl,ddf_bool,hostgal_specz,hostgal_photoz,hostgal_photoz_err,distmod,mwebv,target,...,true_vpec,true_rv,true_av,true_peakmjd,tflux_u,tflux_g,tflux_r,tflux_i,tflux_z,tflux_y
0,615,349.0461,-61.9438,1,0.000,0.000,0.000,-9.000,0.017,92,...,0.0,0.0,0.0,59570.000,484.7,3286.7,3214.1,3039.7,2854.5,2837.0
1,713,53.0859,-27.7844,1,1.818,1.627,0.255,45.406,0.007,88,...,0.0,0.0,0.0,59570.000,108.7,117.7,119.9,149.6,147.9,150.5
2,730,33.5742,-6.5796,1,0.232,0.226,0.016,40.256,0.021,42,...,4.5,0.0,0.0,60444.379,0.0,0.0,0.0,0.0,0.0,0.0
3,745,0.1899,-45.5867,1,0.304,0.281,1.152,40.795,0.007,90,...,257.7,0.0,0.0,60130.453,0.0,0.0,0.0,0.0,0.0,0.0
4,1124,352.7113,-63.8237,1,0.193,0.241,0.018,40.417,0.024,90,...,-368.8,0.0,0.0,60452.641,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7843,130739978,26.7188,-14.9403,0,0.000,0.000,0.000,-9.000,0.013,65,...,0.0,0.0,0.0,59570.000,26.4,267.6,742.8,3295.1,6047.5,7955.2
7844,130755807,120.1013,-62.6967,0,0.172,2.561,1.115,46.611,0.136,90,...,-12.8,0.0,0.0,60056.809,0.0,0.0,0.0,0.0,0.0,0.0
7845,130762946,203.1081,-55.6821,0,0.000,0.000,0.000,-9.000,0.430,16,...,0.0,0.0,0.0,59570.000,83.8,1124.7,1445.1,1191.2,848.9,382.5
7846,130772921,79.1016,-35.5018,0,0.000,0.000,0.000,-9.000,0.034,65,...,0.0,0.0,0.0,59570.000,1.9,14.4,49.4,244.3,534.8,897.2
7847,130779836,301.9922,-17.4263,0,0.000,0.000,0.000,-9.000,0.091,6,...,0.0,0.0,0.0,59905.160,6134.1,23008.9,36299.5,41257.7,43047.7,44230.7

In [53]:
df.isna().sum()

object_id             0
ra                    0
decl                  0
ddf_bool              0
hostgal_specz         0
hostgal_photoz        0
hostgal_photoz_err    0
distmod               0
mwebv                 0
target                0
true_distmod          0
true_lensdmu          0
true_vpec             0
true_rv               0
true_av               0
true_peakmjd          0
tflux_u               0
tflux_g               0
tflux_r               0
tflux_i               0
tflux_z               0
tflux_y               0
dtype: int64

In [54]:
!pip install imblearn
from imblearn.over_sampling import SMOTE
from collections import Counter

Requirement already satisfied: imblearn in c:\users\abc\onedrive\desktop\ml_course\bulldozer-price-time-series-regression\env\lib\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in c:\users\abc\onedrive\desktop\ml_course\bulldozer-price-time-series-regression\env\lib\site-packages (from imblearn) (0.8.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\abc\onedrive\desktop\ml_course\bulldozer-price-time-series-regression\env\lib\site-packages (from imbalanced-learn->imblearn) (1.20.1)
Requirement already satisfied: scipy>=0.19.1 in c:\users\abc\onedrive\desktop\ml_course\bulldozer-price-time-series-regression\env\lib\site-packages (from imbalanced-learn->imblearn) (1.6.2)
Requirement already satisfied: joblib>=0.11 in c:\users\abc\onedrive\desktop\ml_course\bulldozer-price-time-series-regression\env\lib\site-packages (from imbalanced-learn->imblearn) (1.0.1)
Requirement already satisfied: scikit-learn>=0.24 in c:\users\abc\onedrive\desktop\ml_course\bulldozer-price-time-series-regression\env\lib\site-packages (from imbalanced-learn->imblearn) (0.24.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\abc\onedrive\desktop\ml_course\bulldozer-price-time-series-regression\env\lib\site-packages (from scikit-learn>=0.24->imbalanced-learn->imblearn) (2.1.0)

In [55]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop("target", axis=1)
y = df["target"]
oversample = SMOTE()
X, y = oversample.fit_resample(X, y)

counter = Counter(y)
for k,v in counter.items():
  per = v / len(y) * 100

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

scaler = StandardScaler()
scaler.fit(X_train)

X_train = pd.DataFrame(scaler.transform(X_train), columns = X.columns)
X_test = pd.DataFrame(scaler.transform(X_test), columns = X.columns)

In [56]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9016984045290788

In [57]:
preds = model.predict(X_test)

In [58]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
def evaluate_clf(y_true, y_preds):
    '''
    Performs evaluation comparisons on y_true labels vs. y_pred labels 
    on a classification model
    '''
    accuracy = accuracy_score(y_true, y_preds)
    precision = precision_score(y_true, y_preds, average='weighted')
    recall = recall_score(y_true, y_preds, average='weighted')
    f1 = f1_score(y_true, y_preds, average='weighted')
    metric_dict = {"accuracy": round(accuracy, 2),
                   'precision': round(precision, 2),
                   "recall": round(recall, 2),
                   'f1': round(f1, 2)}
    print(f'Accuracy: {accuracy * 100:.2f}%')
    print(f'Precision: {precision:.2f}')
    print(f'Recall: {recall:.2f}')
    print(f'F1: {f1:.2f}')
    
    return metric_dict

In [59]:
model_dict = evaluate_clf(y_test, preds)

Accuracy: 90.17%
Precision: 0.90
Recall: 0.90
F1: 0.90